# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  # false positive:   error - python package "--hash" is available for public registration. /github/workspace/images/superset/requirements.txt
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_DEVSKIM

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity=MEDIUM,HIGH,CRITICAL"
  - "--ignore-unfixed"

REPOSITORY_KICS_CONFIG_FILE: .kics.yaml
REPOSITORY_KICS_ARGUMENTS:
  - --fail-on=HIGH
