name: "Lint PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions: read-all

jobs:
  check-pr-title:
    name: Validate PR title
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@c24d6dd07c69e0826c52021944f216b2e3192535 # v5.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
