name: ci

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      component-name: ${{ steps.component-meta.outputs.component }}
      component-version: ${{ steps.component-meta.outputs.version }}
    steps:
      - id: component-meta
        shell: bash
        env:
          TAG: "${{ github.ref_name }}"
        run: |
          regex="^(.*)-(v[0-9.]*(-.*)?)$"

          if [[ ${TAG} =~ $regex ]]; then
              component_name="${BASH_REMATCH[1]}"
              version="${BASH_REMATCH[2]}"

              echo "Component Name: $component_name"
              echo "Version: $version"

              echo "component=$component_name" >>"$GITHUB_OUTPUT"
              echo "version=$version" >>"$GITHUB_OUTPUT"
          else
              echo "tag format does not match."
              exit 1
          fi

  build:
    uses: miracum/.github/.github/workflows/standard-build.yaml@f4c8b63f01be62f28729c15d6ddffebeb0725fc8 # v1.16.9
    needs:
      - prepare
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      image: ghcr.io/${{ github.repository }}/${{ needs.prepare.outputs.component-name }}
      build-context: images/${{ needs.prepare.outputs.component-name }}
      enable-build-test-layer: false
      enable-upload-test-image: false
      enable-upload-image: false
      image-tags: |
        type=semver,pattern={{raw}},value=${{ needs.prepare.outputs.component-version }}
      enable-trivy-scan: ${{ needs.prepare.outputs.component-name != 'ml-on-fhir' }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
